# Generated by Django 4.0.3 on 2022-03-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0003_cliente_tag_producto_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='camada',
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_creada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='tags',
            field=models.ManyToManyField(to='Prueba.tag'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
