# Generated by Django 4.0.3 on 2022-03-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0004_remove_curso_camada_curso_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
