# Generated by Django 4.0.3 on 2022-03-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0006_cliente_user_alter_curso_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='tags',
        ),
    ]
