# Generated by Django 4.0.3 on 2022-03-19 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Prueba', '0008_remove_curso_categoria_remove_curso_data_creada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Usuario',
        ),
    ]
