# Generated by Django 4.0.3 on 2022-03-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0009_rename_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prueba.curso'),
        ),
    ]
