# Generated by Django 4.0.3 on 2022-03-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0010_alter_order_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Fuera del curso', 'Fuera del curso'), ('Cursando', 'Cursando')], max_length=200, null=True),
        ),
    ]
