# Generated by Django 4.0.3 on 2022-04-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0013_alter_usuario_profile_pic_alter_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tags',
        ),
        migrations.AddField(
            model_name='curso',
            name='tags',
            field=models.ManyToManyField(to='Prueba.tag'),
        ),
    ]
