# Generated by Django 4.0.3 on 2022-04-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0016_alter_order_curso_alter_order_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tag',
            name='nametag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
