# Generated by Django 4.0.3 on 2022-04-09 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0017_remove_tag_nombre_tag_nametag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nametag',
            new_name='nametagmodel',
        ),
    ]
