# Generated by Django 4.0.3 on 2022-04-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0018_rename_nametag_tag_nametagmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='usuario',
            new_name='usuario2',
        ),
    ]
