# Generated by Django 4.0.3 on 2022-04-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0019_rename_usuario_order_usuario2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='usuario2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prueba.usuario'),
        ),
    ]
