# Generated by Django 4.0.3 on 2022-04-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0020_alter_order_usuario2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='usuario2',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='curso',
            new_name='cursada',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='data_creada',
            new_name='fecha',
        ),
    ]
