# Generated by Django 4.0.3 on 2022-04-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0024_rename_nombre_curso_nombre2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nombre2',
            new_name='nombre',
        ),
    ]
