# Generated by Django 4.0.3 on 2022-04-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0029_alter_curso_camada_alter_curso_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
