# Generated by Django 4.0.3 on 2022-04-09 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0030_order_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='nombre',
        ),
    ]
