# Generated by Django 4.0.3 on 2022-04-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0035_alter_order_cursada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Ordenes',
        ),
    ]
