# Generated by Django 4.0.3 on 2022-04-09 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0036_rename_order_ordenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cursada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prueba.curso'),
        ),
    ]
