# Generated by Django 4.0.3 on 2022-04-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0037_usuario_cursada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cursada',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cursada',
            field=models.ManyToManyField(null=True, to='Prueba.curso'),
        ),
    ]
