# Generated by Django 4.0.3 on 2022-04-09 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0038_remove_usuario_cursada_usuario_cursada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordenes',
            new_name='Ordene',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cursada',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cursada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prueba.curso'),
        ),
    ]
