# Generated by Django 4.0.3 on 2022-04-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0040_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cursada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prueba.curso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profile_pic',
            field=models.ImageField(default='profile1.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
