# Generated by Django 4.0.3 on 2022-04-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0042_alter_curso_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='tags',
        ),
    ]
