# Generated by Django 4.0.3 on 2022-04-11 21:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0043_remove_curso_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='presentacion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
