# Generated by Django 4.0.3 on 2022-04-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0044_curso_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
