# Generated by Django 4.0.3 on 2022-04-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0045_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordene',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('En curso', 'En curso')], max_length=200, null=True),
        ),
    ]
